Django/Django_05/실습/todos/urls.py
from django.urls import path
from . import views

app_name = "todos"

urlpatterns = [
    path("", views.index, name="index"),
    path("create/", views.create, name="create"),
    path("delete/<int:pk>", views.delete, name="delete"),
]

Django/Django_05/실습/todos/views.py
from django.shortcuts import render, redirect
from .models import Todo

# Create your views here.
def index(request):
    todos = Todo.objects.all()
    context = {
        "todos": todos,
    }
    return render(request, "todos/index.html", context)


def create(request):
    content = request.GET.get("content")
    priority = request.GET.get("priority")
    deadline = request.GET.get("deadline")
    Todo.objects.create(content=content, priority=priority, deadline=deadline)

    context = {
        "content": content,
        "priority": priority,
        "deadline": deadline,
    }
    return redirect("todos:index")


def delete(request, pk):
    Todo.objects.get(id=pk).delete()
    return redirect("todos:index")

Django/Django_05/실습/todos/templates/todos/index.html
{% extends 'base.html' %}
{% block content %}
<h1>index.html</h1>
<form action="{% url 'todos:create' %}">
  할 일<input type="text" name="content" maxlength="80">
  우선순위<input type="num" name="priority" value="1">
  <input type="date" name="deadline">
  <input type="submit" value="할 일 추가">
</form>
<hr>
<ul>
  {% for todo in todos %}
  <li>
    {{ todo.id }} |
    {{ todo.priority }} |
    {{ todo.content }} |
    {{ todo.created_at }} |
    {{ todo.deadline }} |
    {{ todo.completed }} |
    <a href="">수정</a>
    <a href="{% url 'todos:delete' todo.id %}">삭제</a>
  </li>
</ul>
{% endfor %}
{% endblock %}