Django/Django_08/실습/articles/urls.py
from django.urls import URLPattern, path
from . import views

app_name = "articles"

urlpatterns = [
    path("", views.index, name="index"),
    path("create/", views.create, name="create"),
    path("detail/<int:pk>", views.detail, name="detail"),
    path("delete/<int:pk>", views.delete, name="delete"),
    path("update/<int:pk>", views.update, name="update"),
]

Django/Django_08/실습/pjt/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("articles.urls")),
]

Django/Django_08/실습/articles/views.py
from django.contrib import messages
from django.shortcuts import redirect, render
from articles.forms import ReviewForm
from .models import Review


# Create your views here.


def index(request):
    k = Review.objects.order_by("id")
    context = {
        "v": k,
    }
    return render(request, "articles/index.html", context)


def create(request):
    # if request.method == "GET":
    #     k = request.GET
    #     context = {"k": k}

    #     return render(request, "articles/create.html", context)
    # else:

    #     title = request.POST.get("title")
    #     content = request.POST.get("content")
    #     Review.objects.create(title=title, content=content)

    #     return redirect("/")
    if request.method == "POST":
        ppap_form = ReviewForm(request.POST)
        if ppap_form.is_valid():
            ppap_form.save()
            return redirect("/")
        messages.add_message(request, messages.INFO, "정보를 나타냅니다.")
    else:
        ppap_form = ReviewForm()
    context = {"ppap_form": ppap_form}
    return render(request, "articles/create.html", context)


def detail(request, pk):
    k = Review.objects.get(pk=pk)
    context = {"i": k}
    return render(request, "articles/detail.html", context)


def delete(request, pk):
    Review.objects.get(pk=pk).delete()
    return redirect("/")


def update(request, pk):
    k = Review.objects.get(pk=pk)
    if request.method == "POST":
        #     k.title = request.POST.get("title")
        #     k.content = request.POST.get("content")
        #     k.save()
        #     return redirect("/")

        # else:
        #     context = {"c": k}
        ppap_form = ReviewForm(request.POST, instance=k)
        if ppap_form.is_valid():
            ppap_form.save()
            return redirect("/", k.pk)
    else:
        ppap_form = ReviewForm(instance=k)
    context = {
        "ppap_form": ppap_form,
        "ppap": k,
    }

    return render(request, "articles/update.html", context)

Django/Django_08/실습/articles/templates/articles/create.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/style.css' %}">
<div class="container">
  <h5 class="my-3 border-bottom pb-2">댓글 등록</h5>
  <form method="post" class="post-form my-3">
    <!-- 오류표시 START -->
    <!-- views.py에서 진행한 is_valid가 false일때 경고문!-->
    <!-- {% if form.errors %}
    <div class="alert alert-danger" role="alert">
      {% for field in form %}
      {% if field.errors %}
      <strong>{{ field.label }}</strong>
      {{ field.errors }}
      {% endif %}
      {% endfor %}
    </div>
    {% endif %} -->
    <form action="{% url 'articles:create' %}" method="POST">
      {% csrf_token %}
      {{ ppap_form.as_table }}
      <input type="submit" class="m-2 btn btn-outline-success" value="등록">
      <!-- <label for="title">제목 : </label>
  <input type="text" name="title" id="title">
  <label for="content">내용 : </label>
  <textarea name="content" id="content"></textarea>
  <input type="submit" value="글쓰기"> -->
    </form>
  </form>
  {% endblock %}

Django/Django_08/실습/articles/templates/articles/detail.html
{% extends 'base.html' %}
{% block content %}
<div class="m-5 p-3 border border-3 border-success rounded">
  <h3>제목 : {{i.title}}</h3>
  <h5>내용 : {{i.content}}</h5>
  <p>만든날짜 : {{i.created_at}} | 수정날짜 : {{i.updated_at}}</p>
  <a href="{% url 'articles:delete' i.pk %}" type="button" class="btn btn-outline-success">삭제</a>
  <a href="{% url 'articles:update' i.pk %}" type="button" class="btn btn-outline-success">수정</a>
</div>
{% endblock %}

Django/Django_08/실습/articles/templates/articles/index.html
{% extends 'base.html' %}
{% block content %}
{% load static %}

<head>
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<nav class="navbar bg-light">
  <div class="container-fluid">
    <img src="{% static 'images/Editing-Edit-icon.png' %}" width="30" height="25" class="align-text-top">
    <h1>의견 작성</h1>
    </a>
    <a href="{% url 'articles:create' %}" type="button" class="btn btn-outline-success btn-lg">작성</a>
  </div>
</nav>
<hr>
<form action="" class="m-4">
  <table class="table">
    <thead>
      <tr>
        <th scope="col">리뷰 번호</th>
        <th scope="col">리뷰 제목</th>
        <th scope="col">작성 시간</th>
      </tr>
    </thead>
    <tbody class="table-group-divider">
      {% for i in v %}
      <tr>
        <th scope="row">{{i.id}}</th>
        <td><a href="{% url 'articles:detail' i.pk%}" class="link-success">
            <p class="text-success"> 제목 : {{i.title}}<p>
          </a></td>
        <td>{{i.created_at}}</td>
      </tr>
    </tbody>
    {% endfor%}
  </table>
</form>
<nav aria-label="Page navigation example">
  <ul class="pagination justify-content-center">
    <li class="page-item">
      <a class="page-link" href="#" aria-label="success">
        <span aria-hidden="true">&laquo;</span>
      </a>
    </li>
    <li class="page-item"><a class="page-link" href="#">1</a></li>
    <li class="page-item"><a class="page-link" href="#">2</a></li>
    <li class="page-item"><a class="page-link" href="#">3</a></li>
    <li class="page-item">
      <a class="page-link" href="#" aria-label="Next">
        <span aria-hidden="true">&raquo;</span>
      </a>
    </li>
  </ul>
</nav>
{% endblock %}

Django/Django_08/실습/articles/templates/articles/update.html
{% extends 'base.html' %}
{% block content %}
<form action="{% url 'articles:update' ppap.pk %}" method="POST">
  {% csrf_token %}
  {{ ppap_form.as_table }}
  <input type="submit" class="m-2 btn btn-outline-success" value="등록">
  <!-- <label for="title">제목 : </label>
  <input type="text" name="title" id="title">
  <label for="content">내용 : </label>
  <textarea name="content" id="content"></textarea>
  <input type="submit" value="글쓰기"> -->
</form>
{% endblock %}

Django/Django_08/실습/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, intial-scale=1.0">
  <!-- CSS only -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
  <!-- JavaScript Bundle with Popper -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8"
    crossorigin="anonymous"></script>
  <title>Document</title>
</head>

<body>
  {% block content %}
  {% endblock %}
</body>

</html>