Django/Django_11/221012/accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path("", views.home, name="home"),
    path("signup/", views.signup, name="signup"),
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("<int:pk>/", views.detail, name="detail"),
]

Django/Django_11/221012/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.


class User(AbstractUser):
    pass

Django/Django_11/221012/accounts/forms.py
from django.contrib.auth.forms import UserCreationForm

# from .models import User
from django.contrib.auth import get_user_model


class UsersForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = ("username", "email")

Django/Django_11/221012/accounts/views.py
import imp
from multiprocessing import context
from django.shortcuts import render, redirect
from .models import User
from .forms import UsersForm
from django.contrib.auth import get_user_model
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth.forms import AuthenticationForm

# Create your views here.
def home(request):
    users = User.objects.all()
    context = {
        "users": users,
    }
    return render(request, "accounts/home.html", context)


def signup(request):
    if request.method == "POST":
        form = UsersForm(request.POST)
        if form.is_valid():
            user = form.save()
            auth_login(request, user)
            return redirect("accounts:home")
    else:
        form = UsersForm()
    context = {
        "form": form,
    }
    return render(request, "accounts/signup.html", context)


def login(request):
    if request.method == "POST":
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect(request.GET.get("next") or "accounts:home")
    else:
        form = AuthenticationForm()
    context = {"form": form}
    return render(request, "accounts/login.html", context)


def logout(request):
    auth_logout(request)
    return redirect("accounts:home")


def detail(request, pk):
    user = get_user_model().objects.get(pk=pk)
    context = {
        "user1": user,
    }
    return render(request, "accounts/detail.html", context)

Django/Django_11/221012/accounts/templates/accounts/detail.html
{% extends 'base.html' %}

{% block content %}
  <div class="m-5 p-3 border border-3 border-secondary rounded">
    <h1>{{ user1.username }}의 페이지</h1>
    <h5>{{ user1.email }}</h5>

  {% endblock content %}

Django/Django_11/221012/accounts/templates/accounts/home.html
{% extends 'base.html' %}
{% block content %}
  <div class='container'>
    <table class='table'>
      <thead>
        <tr>
          <th scope='col'>#</th>
          <th scope='col'>username</th>
          <th scope='col'>email</th>
        </tr>
      </thead>
      <tbody>
        {% for user in users %}
          <tr>
            <th scope='row'>{{ user.id }}</th>
            <td>
              <a href="{% url 'accounts:detail' user.pk %}">{{ user.username }}</a>
            </td>
            <td>{{ user.email }}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
  <div class="container">
    <a href="{% url 'accounts:signup' %}" class="btn btn-secondary">회원가입</a>
  </div>
{% endblock %}

Django/Django_11/221012/accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block content %}
  <h1>
    로그인페이지
  </h1>
  <form action="{% url 'accounts:login' %}" method="POST">
    {% csrf_token %}
    <div class="mb-3">
      <label for="id">사용자 아이디</label>
      <input type="text" class="form-control" name="username" id="username">
    </div>
    <div class="mb-3">
      <label for="password">비밀번호</label>
      <input type="password" class="form-control" name="password" id="password">
    </div>
    <div class="mb-3">
      <button type="submit" class="btn btn-outline-secondary">로그인</button>
      <a type="button" class="btn btn-secondary" href="{% url 'accounts:signup' %}">회원가입</a>
    </div>

  </form>

  <!-- 입력 항목 username과 password는 모두 django.contrib.auth 앱에서 요구하는 필수 항목이다. -->
{% endblock %}

Django/Django_11/221012/accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% block content %}
  <div class="content m-3">
    <h1 class="text-center">회원가입</h1>

    <form action="" method="POST">
      {% csrf_token %}
      {% bootstrap_form form %}
      <button type='submit' class="btn btn-secondary">회원가입</button>
    </form>
  </div>
{% endblock %}